[project]
name = "abx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "fastabx>=0.9.0",
    "huggingface-hub>=1.31,<2",
    "ipykernel>=7.4.0",
    "librosa>=1.0.0",
    "matplotlib>=3.11.2",
    "pandas>=3.0.6",
    "seaborn>=0.13.2",
    "soundfile>=0.14.0",
    "torchaudio>=2.11.0",
    "transformers>=5",
]
